version: '3.8'

networks:
  ara_proje_network:
    driver: bridge

services:
  # --- KAFKA ALTYAPISI (Buraya taşındı) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ara_proje_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - ara_proje_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Yerel Kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    networks:
      - ara_proje_network
    depends_on:
      - kafka
      - zookeeper

  # --- DİĞER ALTYAPI ---
  postgres_auth:
    image: postgres:15-alpine
    container_name: postgres_auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: authmicroservicedb
    ports:
      - "5430:5432"
    networks:
      - ara_proje_network
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres_recommender:
    image: postgres:15-alpine
    container_name: postgres_recommender
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: recommender_db
    ports:
      - "5433:5432"
    networks:
      - ara_proje_network
    volumes:
      - postgres_rec_data:/var/lib/postgresql/data

  postgres_userreads:
    image: postgres:15-alpine
    container_name: postgres_userreads
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: UserReads
    ports:
      - "5434:5432"
    networks:
      - ara_proje_network
    volumes:
      - postgres_userreads_data:/var/lib/postgresql/data

  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    networks:
      - ara_proje_network
    environment:
      REDIS_PASSWORD: "!ASD1210*DAsad323.21?AZXnu"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - ara_proje_network

  # --- MİKROSERVİSLER ---
  auth-service:
    build: ./AuthMikroService
    container_name: auth-service
    ports:
      - "8090:8090"
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_auth:5432/authmicroservicedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SECRETEJWTSTRING: "ara123456789proje123456789ara123456789proje123456789"
      APP_SECURITY_API_KEY_HEADER: "X-API-KEY"
      APP_SECURITY_API_KEY_VALUE: "bJNB32JHE4G78CBYcdsc7TX86txbn31cxn67GVXXg8BHCDSBghbhcj"
      AWS_S3_REGION: "eu-north-1"
      AWS_S3_BUCKET: "opt-app-dev"
      AWS_ACCESSKEYID: "AKIA6I7UT46DUIDI7OQ2"
      AWS_SECRETKEY: "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"
      SPRING_MAIL_HOST: "smtp.gmail.com"
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: "omeeryldrmm03@gmail.com"
      SPRING_MAIL_PASSWORD: "ivog exhh oime yued"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "true"
    networks:
      - ara_proje_network
    depends_on:
      - postgres_auth

  fetcher-service:
    build: ./FetcherMicroService
    container_name: fetcher-service
    ports:
      - "8091:8091"
    environment:
      SERVER_PORT: 8091
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: fetcher-group
      KAFKA_TOPIC_NEWS_REQUEST: haber_talebi_topic
      KAFKA_TOPIC_NEWS_PROCESSED: haber_zenginlestirme_topic
      LLM_API_KEY: AIzaSyAXBKULrDW9rTVr68n4NfLU8HjVJNmGYt0
      LLM_API_BASEURL: https://generativelanguage.googleapis.com
    networks:
      - ara_proje_network
    depends_on:
      - kafka

  processor-service:
    build: ./Processor
    container_name: processor-service
    ports:
      - "8003:80"
    environment:
      Kafka__Broker: kafka:9092
      Kafka__ConsumerTopic: haber_zenginlestirme_topic
      Kafka__ProducerTopic: haber_isleme_topic
      HuggingFace__ApiKey: "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"
      HuggingFace__ApiUrl: "https://router.huggingface.co/hf-inference/models/facebook/bart-large-cnn"
    networks:
      - ara_proje_network
    depends_on:
      - kafka

  ai-enrichment-service:
    build: ./ai-enrichment
    container_name: ai-enrichment-service
    ports:
      - "8000:8000"
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC_CONSUME: haber_isleme_topic
      KAFKA_CONSUMER_GROUP: "ai-enrichment-group"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      hf_api_key: "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"
      
    networks:
      - ara_proje_network
    depends_on:
      - elasticsearch
      - kafka

  content-finder-service:
    build: ./content-finder
    container_name: content-finder-service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql://postgres:12345@postgres_userreads:5432/UserReads"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC_NEWS_REQUEST: "haber_talebi_topic"
      RECOMMENDER_SERVICE_URL: "http://recommender-service:8004"
      TRUSTED_API_KEY: "bJNB32JHE4G78CBYcdsc7TX86txbn31cxn67GVXXg8BHCDSBghbhcj"
    networks:
      - ara_proje_network
    depends_on:
      - postgres_userreads
      - elasticsearch
      - kafka

  recommender-service:
    build: ./Recommender
    container_name: recommender-service
    ports:
      - "8004:8004"
    environment:
      PORT: "8004"
      DATABASE_URL: "postgresql://postgres:12345@postgres_recommender:5432/recommender_db"
      REDIS_ADDR: "redis_cache:6379"
      REDIS_PASSWORD: "!ASD1210*DAsad323.21?AZXnu"
      AUTH_SERVICE_URL: "http://auth-service:8090"
      TRUSTED_API_KEY: "bJNB32JHE4G78CBYcdsc7TX86txbn31cxn67GVXXg8BHCDSBghbhcj"
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC_ONBOARDING: "onboarding_events"
      KAFKA_TOPIC_INTERACTION: "interaction_events"
    networks:
      - ara_proje_network
    depends_on:
      - postgres_recommender
      - redis_cache
      - auth-service
      - kafka

volumes:
  postgres_auth_data:
  postgres_rec_data:
  postgres_userreads_data: