spring.application.name=content-mixer

server.port=8092

# --- KAFKA BAĞLANTI AYARLARI ---
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=news-mixer-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# --- DESERIALIZER AYARLARI ---
# Hata durumunda patlamaması için ErrorHandlingDeserializer kullanıyoruz
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Asıl işi yapan sınıflar (Delegate)
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer

# --- PYTHON UYUMLULUĞU ---
# 1. Güvenlik: Tüm paketlere izin ver
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# 2. Python header göndermez, header aramayı kapatıyoruz
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# 3. Header yoksa varsayılan olarak bu sınıfa çevir
spring.kafka.consumer.properties.spring.json.value.default.type=com.content_mixer.dto.FeedPayload

# --- UYGULAMA AYARLARI ---
app.kafka.topic.request=unmixed-feed-topic
app.kafka.topic.reply=mixed-feed-reply-topic