spring.application.name=FetcherMicroService

server.port=8091

spring.kafka.bootstrap-servers=kafka:9092

kafka.topic.news.request=haber_talebi_topic

spring.kafka.consumer.group-id=fetcher-group

spring.kafka.consumer.auto-offset-reset=earliest

kafka.topic.news.processed=haber_zenginlestirme_topic

llm.api.key=AIzaSyAXBKULrDW9rTVr68n4NfLU8HjVJNmGYt0
llm.api.baseurl=https://generativelanguage.googleapis.com
