spring.application.name=FetcherMicroService

server.port=8091

newsapi.key=43949a6324754952bcc9fb9d59875c1a
newsapi.base-url=https://newsapi.org/v2

#ai.enrichment.url=http://127.0.0.1:8000

processor.service.url=http://127.0.0.1:8003