spring.application.name=FetcherMicroService

server.port=8091

# Docker'daki Kafka broker'?na ba?lan (E?er Docker'dan �al??t?r?yorsan 'kafka:9092')
spring.kafka.bootstrap-servers=localhost:29092

# Hangi topic'i dinleyecek (Python'un yazd??? topic)
kafka.topic.news.request=haber_talebi_topic
# Bu servisin t�ketici grubu ad?
spring.kafka.consumer.group-id=fetcher-group
# Kafka'ya ilk kez ba?land???nda en eski mesajdan ba?la (birikmi? 33 mesaj? almak i�in)
spring.kafka.consumer.auto-offset-reset=earliest

# ??lenmi? haberleri hangi topic'e yollayacak
kafka.topic.news.processed=haber_zenginlestirme_topic
