spring.application.name=AuthMikroService

server.port=8090

secreteJwtString=ara123456789proje123456789ara123456789proje123456789
app.security.api-key-header=X-API-KEY
app.security.api-key-value=vGCAHggs623e2dgbGFGfxTRD2561C2CDSANC125csgh

## POSTGRESQL CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/authmicroservicedb
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

## AWS CONFIG
aws.s3.region=eu-north-1
aws.s3.bucket=opt-app-dev
aws.accessKeyId=AKIA6I7UT46DUIDI7OQ2
aws.secretKey=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

## Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omeeryldrmm03@gmail.com
spring.mail.password=ivog exhh oime yued
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true