apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: omerfarukyildirim/auth-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "8090"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-auth:5432/authmicroservicedb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: "12345"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: my-kafka-kafka-bootstrap.kafka:9092
            # EKLENEN KISIM: Java'nın RAM limitini tanıması için (Zorunlu ayar)
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75.0"
          # EKLENEN KISIM: Resource Limits
          resources:
            requests:
              memory: "300Mi"  # Başlangıçta 300MB ayır
              cpu: "200m"
            limits:
              memory: "600Mi"  # En fazla 600MB kullanabilsin (Öncelikli servis)
              cpu: "1000m"
