spring.application.name=AuthMikroService

server.port=8090

secreteJwtString=ara123456789proje123456789ara123456789proje123456789
app.security.api-key-header=X-API-KEY
app.security.api-key-value=bJNB32JHE4G78CBYcdsc7TX86txbn31cxn67GVXXg8BHCDSBghbhcj

## POSTGRESQL CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/authmicroservicedb
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# MinIO Eri?im Bilgileri
aws.accessKeyId=minioadmin      # MinIO kurarken belirledi?in kullan?c? ad?
aws.secretKey=minioadmin        # MinIO kurarken belirledi?in ?ifre
aws.s3.region=us-east-1         # MinIO için genelde fark etmez ama standart b?rak
aws.s3.bucket=my-bucket-name    # MinIO panelinden olu?turdu?un bucket ad?

# MinIO Adresi (Buras? Çok Önemli)
# Localhost'ta çal???rken: http://localhost:9000
# Kubernetes içindeyken: http://minio-service.default.svc.cluster.local:9000 (Service Ad?)
aws.s3.endpoint=http://localhost:9000

## Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omeeryldrmm03@gmail.com
spring.mail.password=ivog exhh oime yued
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

## KAFKA CONF?GURAT?ON
spring.kafka.bootstrap-servers=kafka:9092

# Gï¿½nderirken Key (Anahtar) String olacak
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Gï¿½nderirken Value JSON format?na ï¿½evrilecek (NotificationDTO)
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Hangi grup ad?yla dinleyecek?
spring.kafka.consumer.group-id=notification-group
# Consumer ilk aya?a kalkt???nda eski mesajlar? neresinden okumaya ba?las?n? (earliest: en ba?tan)
spring.kafka.consumer.auto-offset-reset=earliest

Consumer Key Deserializer (Hata korumal?)
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer

# Consumer Value Deserializer (Hata korumal? - As?l olay buras?)
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Gï¿½venilir paketler
spring.kafka.consumer.properties.spring.json.trusted.packages=*