spring.application.name=AuthMikroService

server.port=8090

secreteJwtString=ara123456789proje123456789ara123456789proje123456789
app.security.api-key-header=X-API-KEY
app.security.api-key-value=bJNB32JHE4G78CBYcdsc7TX86txbn31cxn67GVXXg8BHCDSBghbhcj

spring.datasource.url=jdbc:postgresql://localhost:5432/authmicroservicedb
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

aws.accessKeyId=minioadmin      
aws.secretKey=minioadmin       
aws.s3.region=us-east-1         
aws.s3.bucket=my-bucket-name    

aws.s3.endpoint=http://localhost:9000

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


spring.kafka.bootstrap-servers=kafka:9092


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=notification-group

spring.kafka.consumer.auto-offset-reset=earliest

Consumer Key Deserializer (Hata korumal?)
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=20
